/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as SleevingIndexRouteImport } from './routes/sleeving/index'
import { Route as PrintsIndexRouteImport } from './routes/prints/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const SleevingIndexRoute = SleevingIndexRouteImport.update({
  id: '/sleeving/',
  path: '/sleeving/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintsIndexRoute = PrintsIndexRouteImport.update({
  id: '/prints/',
  path: '/prints/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library/': typeof LibraryIndexRoute
  '/prints/': typeof PrintsIndexRoute
  '/sleeving/': typeof SleevingIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryIndexRoute
  '/prints': typeof PrintsIndexRoute
  '/sleeving': typeof SleevingIndexRoute
  '/user': typeof UserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library/': typeof LibraryIndexRoute
  '/prints/': typeof PrintsIndexRoute
  '/sleeving/': typeof SleevingIndexRoute
  '/user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/library/' | '/prints/' | '/sleeving/' | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library' | '/prints' | '/sleeving' | '/user'
  id: '__root__' | '/' | '/library/' | '/prints/' | '/sleeving/' | '/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  PrintsIndexRoute: typeof PrintsIndexRoute
  SleevingIndexRoute: typeof SleevingIndexRoute
  UserIndexRoute: typeof UserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleeving/': {
      id: '/sleeving/'
      path: '/sleeving'
      fullPath: '/sleeving/'
      preLoaderRoute: typeof SleevingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prints/': {
      id: '/prints/'
      path: '/prints'
      fullPath: '/prints/'
      preLoaderRoute: typeof PrintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  PrintsIndexRoute: PrintsIndexRoute,
  SleevingIndexRoute: SleevingIndexRoute,
  UserIndexRoute: UserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
